// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/unauthorized": {
    params: {};
  };
  "/dev-pdf": {
    params: {};
  };
  "/rrhh": {
    params: {};
  };
  "/rrhh/reports_assistance": {
    params: {};
  };
  "/rrhh/liquidation_report": {
    params: {};
  };
  "/rrhh/consolidated_hours_per_worker": {
    params: {};
  };
  "/rrhh/consolidated_hours_per_project": {
    params: {};
  };
  "/rrhh/consolidated_hours_per_worker/pdf": {
    params: {};
  };
  "/rrhh/consolidated_hours_per_project/pdf": {
    params: {};
  };
  "/opportunities": {
    params: {};
  };
  "/opportunities/new-opportunity": {
    params: {};
  };
  "/opportunities/:id/resumen": {
    params: {
      "id": string;
    };
  };
  "/opportunities/:id/information": {
    params: {
      "id": string;
    };
  };
  "/opportunities/:id/phases": {
    params: {
      "id": string;
    };
  };
  "/opportunities/:id/conditions": {
    params: {
      "id": string;
    };
  };
  "/opportunities/:id/report": {
    params: {
      "id": string;
    };
  };
  "/opportunities/:id/quotes/items": {
    params: {
      "id": string;
    };
  };
  "/opportunities/:id/quotes/materials": {
    params: {
      "id": string;
    };
  };
  "/projects": {
    params: {};
  };
  "/projects/new-daily-report": {
    params: {};
  };
  "/projects/:id/resumen": {
    params: {
      "id": string;
    };
  };
  "/projects/:id/information": {
    params: {
      "id": string;
    };
  };
  "/projects/:id/budget/items": {
    params: {
      "id": string;
    };
  };
  "/projects/:id/budget/materials": {
    params: {
      "id": string;
    };
  };
  "/projects/:id/planning": {
    params: {
      "id": string;
    };
  };
  "/projects/:id/daily_reports": {
    params: {
      "id": string;
    };
  };
  "/materials": {
    params: {};
  };
  "/materials/new-material": {
    params: {};
  };
  "/materials/:id": {
    params: {
      "id": string;
    };
  };
  "/materials/:id/prices": {
    params: {
      "id": string;
    };
  };
  "/settings": {
    params: {};
  };
  "/settings/generals": {
    params: {};
  };
  "/settings/calendar": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/unauthorized" | "/dev-pdf" | "/rrhh" | "/rrhh/reports_assistance" | "/rrhh/liquidation_report" | "/rrhh/consolidated_hours_per_worker" | "/rrhh/consolidated_hours_per_project" | "/rrhh/consolidated_hours_per_worker/pdf" | "/rrhh/consolidated_hours_per_project/pdf" | "/opportunities" | "/opportunities/new-opportunity" | "/opportunities/:id/resumen" | "/opportunities/:id/information" | "/opportunities/:id/phases" | "/opportunities/:id/conditions" | "/opportunities/:id/report" | "/opportunities/:id/quotes/items" | "/opportunities/:id/quotes/materials" | "/projects" | "/projects/new-daily-report" | "/projects/:id/resumen" | "/projects/:id/information" | "/projects/:id/budget/items" | "/projects/:id/budget/materials" | "/projects/:id/planning" | "/projects/:id/daily_reports" | "/materials" | "/materials/new-material" | "/materials/:id" | "/materials/:id/prices" | "/settings" | "/settings/generals" | "/settings/calendar";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/unauthorizedPage.tsx": {
    id: "routes/unauthorizedPage";
    page: "/unauthorized";
  };
  "routes/dev-pdf.tsx": {
    id: "routes/dev-pdf";
    page: "/dev-pdf";
  };
  "layouts/main.tsx": {
    id: "layouts/main";
    page: "/" | "/rrhh" | "/rrhh/reports_assistance" | "/rrhh/liquidation_report" | "/rrhh/consolidated_hours_per_worker" | "/rrhh/consolidated_hours_per_project" | "/rrhh/consolidated_hours_per_worker/pdf" | "/rrhh/consolidated_hours_per_project/pdf" | "/opportunities" | "/opportunities/new-opportunity" | "/opportunities/:id/resumen" | "/opportunities/:id/information" | "/opportunities/:id/phases" | "/opportunities/:id/conditions" | "/opportunities/:id/report" | "/opportunities/:id/quotes/items" | "/opportunities/:id/quotes/materials" | "/projects" | "/projects/new-daily-report" | "/projects/:id/resumen" | "/projects/:id/information" | "/projects/:id/budget/items" | "/projects/:id/budget/materials" | "/projects/:id/planning" | "/projects/:id/daily_reports" | "/materials" | "/materials/new-material" | "/materials/:id" | "/materials/:id/prices" | "/settings" | "/settings/generals" | "/settings/calendar";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/rrhh/home.tsx": {
    id: "routes/rrhh/home";
    page: "/rrhh";
  };
  "routes/rrhh/reports_assistance.tsx": {
    id: "routes/rrhh/reports_assistance";
    page: "/rrhh/reports_assistance";
  };
  "routes/rrhh/liquidation_report.tsx": {
    id: "routes/rrhh/liquidation_report";
    page: "/rrhh/liquidation_report";
  };
  "routes/rrhh/consolidated_hours_per_worker.tsx": {
    id: "routes/rrhh/consolidated_hours_per_worker";
    page: "/rrhh/consolidated_hours_per_worker";
  };
  "routes/rrhh/consolidated_hours_per_project.tsx": {
    id: "routes/rrhh/consolidated_hours_per_project";
    page: "/rrhh/consolidated_hours_per_project";
  };
  "routes/rrhh/consolidated_hours_per_worker_pdf.tsx": {
    id: "routes/rrhh/consolidated_hours_per_worker_pdf";
    page: "/rrhh/consolidated_hours_per_worker/pdf";
  };
  "routes/rrhh/consolidated_hours_per_project_pdf.tsx": {
    id: "routes/rrhh/consolidated_hours_per_project_pdf";
    page: "/rrhh/consolidated_hours_per_project/pdf";
  };
  "routes/opportunities/home.tsx": {
    id: "routes/opportunities/home";
    page: "/opportunities";
  };
  "routes/opportunities/new-opportunity.tsx": {
    id: "routes/opportunities/new-opportunity";
    page: "/opportunities/new-opportunity";
  };
  "layouts/opportunity.tsx": {
    id: "layouts/opportunity";
    page: "/opportunities/:id/resumen" | "/opportunities/:id/information" | "/opportunities/:id/phases" | "/opportunities/:id/conditions" | "/opportunities/:id/report" | "/opportunities/:id/quotes/items" | "/opportunities/:id/quotes/materials";
  };
  "routes/opportunities/resumen.tsx": {
    id: "routes/opportunities/resumen";
    page: "/opportunities/:id/resumen";
  };
  "routes/opportunities/information.tsx": {
    id: "routes/opportunities/information";
    page: "/opportunities/:id/information";
  };
  "routes/opportunities/phases.tsx": {
    id: "routes/opportunities/phases";
    page: "/opportunities/:id/phases";
  };
  "routes/opportunities/conditions.tsx": {
    id: "routes/opportunities/conditions";
    page: "/opportunities/:id/conditions";
  };
  "routes/opportunities/report.tsx": {
    id: "routes/opportunities/report";
    page: "/opportunities/:id/report";
  };
  "routes/opportunities/quotes.tsx": {
    id: "routes/opportunities/quotes";
    page: "/opportunities/:id/quotes/items" | "/opportunities/:id/quotes/materials";
  };
  "routes/opportunities/quotes/items.tsx": {
    id: "routes/opportunities/quotes/items";
    page: "/opportunities/:id/quotes/items";
  };
  "routes/opportunities/quotes/materials.tsx": {
    id: "routes/opportunities/quotes/materials";
    page: "/opportunities/:id/quotes/materials";
  };
  "routes/projects/home.tsx": {
    id: "routes/projects/home";
    page: "/projects";
  };
  "routes/projects/new-daily-report.tsx": {
    id: "routes/projects/new-daily-report";
    page: "/projects/new-daily-report";
  };
  "layouts/project.tsx": {
    id: "layouts/project";
    page: "/projects/:id/resumen" | "/projects/:id/information" | "/projects/:id/budget/items" | "/projects/:id/budget/materials" | "/projects/:id/planning" | "/projects/:id/daily_reports";
  };
  "routes/projects/resumen.tsx": {
    id: "routes/projects/resumen";
    page: "/projects/:id/resumen";
  };
  "routes/projects/information.tsx": {
    id: "routes/projects/information";
    page: "/projects/:id/information";
  };
  "routes/projects/budget.tsx": {
    id: "routes/projects/budget";
    page: "/projects/:id/budget/items" | "/projects/:id/budget/materials";
  };
  "routes/projects/budget/items.tsx": {
    id: "routes/projects/budget/items";
    page: "/projects/:id/budget/items";
  };
  "routes/projects/budget/materials.tsx": {
    id: "routes/projects/budget/materials";
    page: "/projects/:id/budget/materials";
  };
  "routes/projects/planning.tsx": {
    id: "routes/projects/planning";
    page: "/projects/:id/planning";
  };
  "routes/projects/daily_reports.tsx": {
    id: "routes/projects/daily_reports";
    page: "/projects/:id/daily_reports";
  };
  "routes/materials/home.tsx": {
    id: "routes/materials/home";
    page: "/materials";
  };
  "routes/materials/new-material.tsx": {
    id: "routes/materials/new-material";
    page: "/materials/new-material";
  };
  "layouts/material.tsx": {
    id: "layouts/material";
    page: "/materials/:id" | "/materials/:id/prices";
  };
  "routes/materials/material.tsx": {
    id: "routes/materials/material";
    page: "/materials/:id";
  };
  "routes/materials/prices.tsx": {
    id: "routes/materials/prices";
    page: "/materials/:id/prices";
  };
  "routes/settings/home.tsx": {
    id: "routes/settings/home";
    page: "/settings";
  };
  "routes/settings/generals.tsx": {
    id: "routes/settings/generals";
    page: "/settings/generals";
  };
  "routes/settings/calendar.tsx": {
    id: "routes/settings/calendar";
    page: "/settings/calendar";
  };
};