// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/unauthorized": {
    params: {};
  };
  "/opportunities": {
    params: {};
  };
  "/materials": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/new-opportunity": {
    params: {};
  };
  "/new-material": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/daily_reports": {
    params: {};
  };
  "/rrhh": {
    params: {};
  };
  "/rrhh/reports_assistance": {
    params: {};
  };
  "/opportunity/:id/resumen": {
    params: {
      "id": string;
    };
  };
  "/opportunity/:id/information": {
    params: {
      "id": string;
    };
  };
  "/opportunity/:id/phases": {
    params: {
      "id": string;
    };
  };
  "/opportunity/:id/conditions": {
    params: {
      "id": string;
    };
  };
  "/opportunity/:id/report": {
    params: {
      "id": string;
    };
  };
  "/opportunity/:id/quotes/items": {
    params: {
      "id": string;
    };
  };
  "/opportunity/:id/quotes/materials": {
    params: {
      "id": string;
    };
  };
  "/project/:id/resumen": {
    params: {
      "id": string;
    };
  };
  "/project/:id/information": {
    params: {
      "id": string;
    };
  };
  "/project/:id/budget/items": {
    params: {
      "id": string;
    };
  };
  "/project/:id/budget/materials": {
    params: {
      "id": string;
    };
  };
  "/project/:id/planning": {
    params: {
      "id": string;
    };
  };
  "/project/:id/daily_reports": {
    params: {
      "id": string;
    };
  };
  "/material/:id": {
    params: {
      "id": string;
    };
  };
  "/material/:id/prices": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/unauthorized" | "/opportunities" | "/materials" | "/settings" | "/new-opportunity" | "/new-material" | "/projects" | "/daily_reports" | "/rrhh" | "/rrhh/reports_assistance" | "/opportunity/:id/resumen" | "/opportunity/:id/information" | "/opportunity/:id/phases" | "/opportunity/:id/conditions" | "/opportunity/:id/report" | "/opportunity/:id/quotes/items" | "/opportunity/:id/quotes/materials" | "/project/:id/resumen" | "/project/:id/information" | "/project/:id/budget/items" | "/project/:id/budget/materials" | "/project/:id/planning" | "/project/:id/daily_reports" | "/material/:id" | "/material/:id/prices";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/unauthorizedPage.tsx": {
    id: "routes/unauthorizedPage";
    page: "/unauthorized";
  };
  "layouts/main.tsx": {
    id: "layouts/main";
    page: "/" | "/opportunities" | "/materials" | "/settings" | "/new-opportunity" | "/new-material" | "/projects" | "/daily_reports" | "/rrhh" | "/rrhh/reports_assistance" | "/opportunity/:id/resumen" | "/opportunity/:id/information" | "/opportunity/:id/phases" | "/opportunity/:id/conditions" | "/opportunity/:id/report" | "/opportunity/:id/quotes/items" | "/opportunity/:id/quotes/materials" | "/project/:id/resumen" | "/project/:id/information" | "/project/:id/budget/items" | "/project/:id/budget/materials" | "/project/:id/planning" | "/project/:id/daily_reports" | "/material/:id" | "/material/:id/prices";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/opportunities.tsx": {
    id: "routes/opportunities";
    page: "/opportunities";
  };
  "routes/materials.tsx": {
    id: "routes/materials";
    page: "/materials";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/newOpportunity.tsx": {
    id: "routes/newOpportunity";
    page: "/new-opportunity";
  };
  "routes/newMaterial.tsx": {
    id: "routes/newMaterial";
    page: "/new-material";
  };
  "routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
  "routes/daily_reports.tsx": {
    id: "routes/daily_reports";
    page: "/daily_reports";
  };
  "routes/rrhh/home.tsx": {
    id: "routes/rrhh/home";
    page: "/rrhh";
  };
  "routes/rrhh/reports_assistance.tsx": {
    id: "routes/rrhh/reports_assistance";
    page: "/rrhh/reports_assistance";
  };
  "layouts/opportunity.tsx": {
    id: "layouts/opportunity";
    page: "/opportunity/:id/resumen" | "/opportunity/:id/information" | "/opportunity/:id/phases" | "/opportunity/:id/conditions" | "/opportunity/:id/report" | "/opportunity/:id/quotes/items" | "/opportunity/:id/quotes/materials";
  };
  "routes/opportunity/resumen.tsx": {
    id: "routes/opportunity/resumen";
    page: "/opportunity/:id/resumen";
  };
  "routes/opportunity/information.tsx": {
    id: "routes/opportunity/information";
    page: "/opportunity/:id/information";
  };
  "routes/opportunity/phases.tsx": {
    id: "routes/opportunity/phases";
    page: "/opportunity/:id/phases";
  };
  "routes/opportunity/conditions.tsx": {
    id: "routes/opportunity/conditions";
    page: "/opportunity/:id/conditions";
  };
  "routes/opportunity/report.tsx": {
    id: "routes/opportunity/report";
    page: "/opportunity/:id/report";
  };
  "routes/opportunity/quotes.tsx": {
    id: "routes/opportunity/quotes";
    page: "/opportunity/:id/quotes/items" | "/opportunity/:id/quotes/materials";
  };
  "routes/opportunity/quotes/items.tsx": {
    id: "routes/opportunity/quotes/items";
    page: "/opportunity/:id/quotes/items";
  };
  "routes/opportunity/quotes/materials.tsx": {
    id: "routes/opportunity/quotes/materials";
    page: "/opportunity/:id/quotes/materials";
  };
  "layouts/project.tsx": {
    id: "layouts/project";
    page: "/project/:id/resumen" | "/project/:id/information" | "/project/:id/budget/items" | "/project/:id/budget/materials" | "/project/:id/planning" | "/project/:id/daily_reports";
  };
  "routes/project/resumen.tsx": {
    id: "routes/project/resumen";
    page: "/project/:id/resumen";
  };
  "routes/project/information.tsx": {
    id: "routes/project/information";
    page: "/project/:id/information";
  };
  "routes/project/budget.tsx": {
    id: "routes/project/budget";
    page: "/project/:id/budget/items" | "/project/:id/budget/materials";
  };
  "routes/project/budget/items.tsx": {
    id: "routes/project/budget/items";
    page: "/project/:id/budget/items";
  };
  "routes/project/budget/materials.tsx": {
    id: "routes/project/budget/materials";
    page: "/project/:id/budget/materials";
  };
  "routes/project/planning.tsx": {
    id: "routes/project/planning";
    page: "/project/:id/planning";
  };
  "routes/project/daily_reports.tsx": {
    id: "routes/project/daily_reports";
    page: "/project/:id/daily_reports";
  };
  "layouts/material.tsx": {
    id: "layouts/material";
    page: "/material/:id" | "/material/:id/prices";
  };
  "routes/material/material.tsx": {
    id: "routes/material/material";
    page: "/material/:id";
  };
  "routes/material/prices.tsx": {
    id: "routes/material/prices";
    page: "/material/:id/prices";
  };
};