// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/opportunities": {
    params: {};
  };
  "/materials": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/new-opportunity": {
    params: {};
  };
  "/new-material": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/opportunity/:id/resumen": {
    params: {
      "id": string;
    };
  };
  "/opportunity/:id/information": {
    params: {
      "id": string;
    };
  };
  "/opportunity/:id/phases": {
    params: {
      "id": string;
    };
  };
  "/opportunity/:id/conditions": {
    params: {
      "id": string;
    };
  };
  "/opportunity/:id/report": {
    params: {
      "id": string;
    };
  };
  "/opportunity/:id/quotes/items": {
    params: {
      "id": string;
    };
  };
  "/opportunity/:id/quotes/materials": {
    params: {
      "id": string;
    };
  };
  "/material/:id": {
    params: {
      "id": string;
    };
  };
  "/material/:id/prices": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/opportunities" | "/materials" | "/settings" | "/new-opportunity" | "/new-material" | "/projects" | "/opportunity/:id/resumen" | "/opportunity/:id/information" | "/opportunity/:id/phases" | "/opportunity/:id/conditions" | "/opportunity/:id/report" | "/opportunity/:id/quotes/items" | "/opportunity/:id/quotes/materials" | "/material/:id" | "/material/:id/prices";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "layouts/main.tsx": {
    id: "layouts/main";
    page: "/" | "/opportunities" | "/materials" | "/settings" | "/new-opportunity" | "/new-material" | "/projects" | "/opportunity/:id/resumen" | "/opportunity/:id/information" | "/opportunity/:id/phases" | "/opportunity/:id/conditions" | "/opportunity/:id/report" | "/opportunity/:id/quotes/items" | "/opportunity/:id/quotes/materials" | "/material/:id" | "/material/:id/prices";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/opportunities.tsx": {
    id: "routes/opportunities";
    page: "/opportunities";
  };
  "routes/materials.tsx": {
    id: "routes/materials";
    page: "/materials";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/newOpportunity.tsx": {
    id: "routes/newOpportunity";
    page: "/new-opportunity";
  };
  "routes/newMaterial.tsx": {
    id: "routes/newMaterial";
    page: "/new-material";
  };
  "routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
  "layouts/opportunity.tsx": {
    id: "layouts/opportunity";
    page: "/opportunity/:id/resumen" | "/opportunity/:id/information" | "/opportunity/:id/phases" | "/opportunity/:id/conditions" | "/opportunity/:id/report" | "/opportunity/:id/quotes/items" | "/opportunity/:id/quotes/materials";
  };
  "routes/opportunity/resumen.tsx": {
    id: "routes/opportunity/resumen";
    page: "/opportunity/:id/resumen";
  };
  "routes/opportunity/information.tsx": {
    id: "routes/opportunity/information";
    page: "/opportunity/:id/information";
  };
  "routes/opportunity/phases.tsx": {
    id: "routes/opportunity/phases";
    page: "/opportunity/:id/phases";
  };
  "routes/opportunity/conditions.tsx": {
    id: "routes/opportunity/conditions";
    page: "/opportunity/:id/conditions";
  };
  "routes/opportunity/report.tsx": {
    id: "routes/opportunity/report";
    page: "/opportunity/:id/report";
  };
  "routes/opportunity/quotes.tsx": {
    id: "routes/opportunity/quotes";
    page: "/opportunity/:id/quotes/items" | "/opportunity/:id/quotes/materials";
  };
  "routes/opportunity/quotes/items.tsx": {
    id: "routes/opportunity/quotes/items";
    page: "/opportunity/:id/quotes/items";
  };
  "routes/opportunity/quotes/materials.tsx": {
    id: "routes/opportunity/quotes/materials";
    page: "/opportunity/:id/quotes/materials";
  };
  "layouts/material.tsx": {
    id: "layouts/material";
    page: "/material/:id" | "/material/:id/prices";
  };
  "routes/material/material.tsx": {
    id: "routes/material/material";
    page: "/material/:id";
  };
  "routes/material/prices.tsx": {
    id: "routes/material/prices";
    page: "/material/:id/prices";
  };
};