import type { Route } from "../+types/root";
import PDFConsolidatedPerWorker from "~/PDF/PDFConsolidatedPerWorker";
import { type ReportMode } from "~/components/Specific/ModelDescription";
import type { ConsolidatedData } from "./rrhh/consolidated_hours_per_worker";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Consolidados por Trabajador" },
    { name: "description", content: "Consolidados por Trabajador [Informes]" },
  ];
}

const data: ConsolidatedData[] = [
  {
    employee_name: "REINHEIMER, CARLOS AUGUSTO",
    total_equivalent_hours: 19.5,
    total_viaticum: 0,
    total_equivalent_days: 2.17,
    alimentation: 1,
    projects: [
      {
        project_name: "Oportunidad: Capacitación 1",
        equivalent_hours: 19.5,
        viaticum: 0,
        dayReport: [
          {
            id: 196,
            created_at: "2026-02-18T17:25:43.324918+00:00",
            id_daily_report: 100,
            id_employee: 19,
            created_by: "00ab86d9-8e0c-474d-aa7b-01fe231178ee",
            observation: "",
            hour_start: "07:00:00",
            hour_end: "20:00:00",
            absent: false,
            date_report: "2026-02-07",
            id_phase: 61,
            phase_name: "Capacitación 1 Etapa A",
            id_project: 29,
            viaticum: false,
            project_name: "Oportunidad: Capacitación 1",
            hours_worked: 13,
            employee: {
              id: 19,
              contacto_id: 436,
              legajo: "",
              puesto: "Coordinador",
              fecha_ingreso: "2020-01-01",
              fecha_egreso: null,
              tipo_contrato: "RELACION_DEPENDENCIA",
              categoria: "",
              salario_basico: null,
              fecha_nacimiento: null,
              estado_civil: "",
              nivel_estudios: "",
              contacto_emergencia: "",
              banco: "",
              cbu: "",
              alias_cbu: "",
              observaciones: "",
              created_at: null,
              updated_at: null,
              contacto_nombre: "REINHEIMER, CARLOS AUGUSTO",
              contacto_cuit: "20260729870",
              contacto_email: "carlosr@imindustrial.com.ar",
              contacto_telefono: "",
              is_precarga: true,
            },
            equivalent_hours: 19.5,
            day_type: "saturday",
          },
           {
            id: 196,
            created_at: "2026-02-18T17:25:43.324918+00:00",
            id_daily_report: 100,
            id_employee: 19,
            created_by: "00ab86d9-8e0c-474d-aa7b-01fe231178ee",
            observation: "",
            hour_start: "07:00:00",
            hour_end: "20:00:00",
            absent: false,
            date_report: "2026-02-07",
            id_phase: 61,
            phase_name: "Capacitación 1 Etapa A",
            id_project: 29,
            viaticum: false,
            project_name: "Oportunidad: Capacitación 1",
            hours_worked: 13,
            employee: {
              id: 19,
              contacto_id: 436,
              legajo: "",
              puesto: "Coordinador",
              fecha_ingreso: "2020-01-01",
              fecha_egreso: null,
              tipo_contrato: "RELACION_DEPENDENCIA",
              categoria: "",
              salario_basico: null,
              fecha_nacimiento: null,
              estado_civil: "",
              nivel_estudios: "",
              contacto_emergencia: "",
              banco: "",
              cbu: "",
              alias_cbu: "",
              observaciones: "",
              created_at: null,
              updated_at: null,
              contacto_nombre: "REINHEIMER, CARLOS AUGUSTO",
              contacto_cuit: "20260729870",
              contacto_email: "carlosr@imindustrial.com.ar",
              contacto_telefono: "",
              is_precarga: true,
            },
            equivalent_hours: 19.5,
            day_type: "saturday",
          },
        ],
        equivalent_days: 2.17,
        alimentation: 1,
      },
    ],
  },
  {
    employee_name: "Villalba Cristian",
    total_equivalent_hours: 10.5,
    total_viaticum: 0,
    total_equivalent_days: 1.17,
    alimentation: 1,
    projects: [
      {
        project_name:
          "251209 Reacondicionamiento frigorífico de sector empaque de despostada",
        equivalent_hours: 10.5,
        viaticum: 0,
        dayReport: [
          {
            id: 188,
            created_at: "2025-12-30T13:56:51.838321+00:00",
            id_daily_report: 93,
            id_employee: 23,
            created_by: "aab3a81e-f3c9-49d3-bd39-3c881ca102fd",
            observation: "maso",
            hour_start: "07:00:00",
            hour_end: "17:00:00",
            absent: false,
            date_report: "2025-12-30",
            id_phase: 68,
            phase_name: "Evaporador Nuevo",
            id_project: 31,
            viaticum: false,
            project_name:
              "251209 Reacondicionamiento frigorífico de sector empaque de despostada",
            hours_worked: 10,
            employee: {
              id: 23,
              contacto_id: 1288,
              legajo: "",
              puesto: "",
              fecha_ingreso: "2025-12-15",
              fecha_egreso: null,
              tipo_contrato: "",
              categoria: "",
              salario_basico: null,
              fecha_nacimiento: null,
              estado_civil: "",
              nivel_estudios: "",
              contacto_emergencia: "",
              banco: "",
              cbu: "",
              alias_cbu: "",
              observaciones: "",
              created_at: null,
              updated_at: null,
              contacto_nombre: "Villalba Cristian",
              contacto_cuit: "",
              contacto_email: "",
              contacto_telefono: "",
              is_precarga: false,
            },
            equivalent_hours: 10.5,
            day_type: "weekday",
          },
        ],
        equivalent_days: 1.17,
        alimentation: 1,
      },
    ],
  },
  {
    employee_name: "Salas Luis",
    total_equivalent_hours: 9,
    total_viaticum: 0,
    total_equivalent_days: 1,
    alimentation: 1,
    projects: [
      {
        project_name:
          "251103 Instalación Evaporadores Antecamara de exportación - Planta San Jorge",
        equivalent_hours: 9,
        viaticum: 0,
        dayReport: [
          {
            id: 187,
            created_at: "2025-12-12T14:16:33.372258+00:00",
            id_daily_report: 92,
            id_employee: 11,
            created_by: "ed9dbe74-05d8-4e72-bb15-d8ca97ad7881",
            observation: "",
            hour_start: "07:00:00",
            hour_end: "16:00:00",
            absent: false,
            date_report: "2025-12-11",
            id_phase: 62,
            phase_name: "Evaporadores",
            id_project: 30,
            viaticum: false,
            project_name:
              "251103 Instalación Evaporadores Antecamara de exportación - Planta San Jorge",
            hours_worked: 9,
            employee: {
              id: 11,
              contacto_id: 1186,
              legajo: "",
              puesto: "Operario",
              fecha_ingreso: "2025-01-01",
              fecha_egreso: null,
              tipo_contrato: "",
              categoria: "",
              salario_basico: null,
              fecha_nacimiento: null,
              estado_civil: "",
              nivel_estudios: "",
              contacto_emergencia: "",
              banco: "",
              cbu: "",
              alias_cbu: "",
              observaciones: "",
              created_at: null,
              updated_at: null,
              contacto_nombre: "Salas Luis",
              contacto_cuit: "",
              contacto_email: "",
              contacto_telefono: "",
              is_precarga: true,
            },
            equivalent_hours: 9,
            day_type: "weekday",
          },
        ],
        equivalent_days: 1,
        alimentation: 1,
      },
    ],
  },
];
const periodo = {
  from: "2025-12-01",
  to: "2026-02-07",
};
export default function Report() {
  return (
    <div className="w-full mt-8 mx-auto flex gap-6 px-8">
      <div className="w-full">
        <PDFConsolidatedPerWorker
          title={"Consolidado de horas por trabajadores"}
          data={data}
          periodo={periodo}
        />
      </div>
    </div>
  );
}
